export const ActionsTypes = {
  FETCH_NEWSLISTS: "FETCH_NEWSLISTS",
  FETCH_NEWSLISTS_SUCCESS: "FETCH_NEWSLISTS_SUCCESS",
  FETCH_NEWSLISTS_FAILED: "FETCH_NEWSLISTS_FAILED",

  UPDATE_NEWSLISTS: "UPDATE_NEWSLISTS",
  UPDATE_NEWSLISTS_SUCCESS: "UPDATE_NEWSLISTS_SUCCESS",
  UPDATE_NEWSLISTS_FAILED: "UPDATE_NEWSLISTS_FAILED",
};
